name = "FMIBuild"
uuid = "226f0e26-6dd6-4589-ada7-1d32f6e1d800"
authors = ["TT <tobias.thummerer@informatik.uni-augsburg.de>", "LM <lars.mikelsons@informatik.uni-augsburg.de>"]
version = "0.1.0"

[deps]
FMICore = "8af89139-c281-408e-bce2-3005eb87462f"
PackageCompiler = "9b87118b-4619-50d2-8e1e-99f35a4d4d9d"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
ZipFile = "a5390f91-8eb1-5f08-bee0-b1d1ffed6cea"

[compat]
FMICore = "0.6.0"
PackageCompiler = "2.0.4"
Pkg = "^1.6.2"
ZipFile = "0.9.4"
julia = "1.6"
